- .github/workflows/build-openstack-baremetal-operator.yaml
We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.
> Drop paths-ignore from build operator workflow

- .ci-operator.yaml
Adds the .ci-operator.yaml config to be used by prow jobs.
> Add build_root_image config for prow jobs

- pkg/openstackbaremetalset/baremetalhost.go
When generating the default networkdata, handle empty vlaue, else it fails with "<len .CtlplaneDnsSearch>: error calling len: reflect: call of reflect.Value.Type on zero Value"}"
> Handle empty dnsSearchDomains

- api/v1beta1/openstackbaremetalset_types.go
Adds `omitempty` to OSBMS `baremetalHosts` map and fixes the existing `omitempty` tags on OSBMS `networkData` and `userData`
> Fix a few 'omitempty' tags in OSBMS

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- controllers/openstackbaremetalset_controller.go
- controllers/openstackprovisionserver_controller.go
The current logic when provisionserver is not provided is to create a provisionserver. It looks for CBO kind provisionings.metal3.io which does not exist when not using CBO.
Also caters for labels going beyond 63 chars.
"spec.selector.matchLabels: Invalid value:
edpm-compute-provisionserver-openstackprovisionserver-deployment: must be no more than 63 characters"
> Allow user provided provisioning interface

- config/rbac/role.yaml
- controllers/openstackprovisionserver_controller.go
- pkg/openstackprovisionserver/deployment.go
I was able to get the `OpenStackProvisionServer` to work with a slimmer permissions requirement.  We no longer require `privileged` SCC nor to run the Apache container as root.
> Improve security by using 'hostnetwork' instead of 'privileged'

- config/manifests/bases/openstack-baremetal-operator.clusterserviceversion.yaml
This should hide the baremetal package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.
> CSV: Set operator-type: non-standalone

- api/v1beta1/openstackbaremetalset_webhook.go
Both OSImage and ProvisionServerName are optional and they work as below.
1. Existing ProvisionServer used if ProvisionServerName in spec
2. Else, if OSImage in spec it would be used, but it should be available locally in the init container running with OSContainerImageURL.
3. If none of them are there in the spec, OS_IMAGE_DEFAULT in OS_CONTAINER_IMAGE_URL_DEFAULT would be used. Both can be patched in csv ENV or their defaults would be used.
> Drop webhook validation for OSImage

- controllers/openstackprovisionserver_controller.go
This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.
> Watch RBAC resources to trigger reconcile

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
Just wanted to add some comments to `CtlPlaneInterface` and `ProvisioningInterface` fields in the `OSBMS` to better distinguish them from one another and clarify their purposes.
> Clarifying comments for OSBMS interface fields

- renovate.json
This pins k8s and controller runtime to be in sync with lib-common and configure renovate to keep the pin
> Configure renovate to pin k8s and controller-runtime for dev preview

- config/default/manager_auth_proxy_patch.yaml
- config/manager/controller_manager_config.yaml
- config/manager/manager.yaml
As we're running a single replica for the controller manager we probably don't need leader election. If we configure more replicas in the future maybe we could use an ENV var.
> Remove leader election for controller

- config/manifests/bases/openstack-baremetal-operator.clusterserviceversion.yaml
The existing link is invalid. Also maturity was not consistent with API version(v1beta) currently presented by this operator.
> Fix link and maturity in csv

- .ci-operator.yaml
- .github/create_bundle.sh
- .github/workflows/build-openstack-baremetal-operator.yaml
- .prow_ci.env
- api/v1beta1/openstackprovisionserver_types.go
- config/default/manager_default_images.yaml
- config/manifests/bases/openstack-baremetal-operator.clusterserviceversion.yaml
- config/samples/baremetal_v1beta1_openstackprovisionserver.yaml
This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
Also, bumps to operator-sdk-1.31 since this operator has artifacts from registry.redhat.io that require auth to work to obtain the sha's
(NOTE: this currently requires a secure registry)
Jira: [OSP-26486](https://issues.redhat.com//browse/OSP-26486)
> Support disconnected network environments

- .github/workflows/build-openstack-baremetal-operator.yaml
Fix to allow the github workflow for bundles to login to the redhat registry. This is required in order to obtain the correct SHA265 info for containers used from there
> Login to registry.redhat.io for bundle builds

- .github/workflows/build-openstack-baremetal-operator.yaml
renovate will bump the openstack-operator even if there was no build done. Lets always build images.
> Always build images

- config/manifests/bases/openstack-baremetal-operator.clusterserviceversion.yaml
Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)
> required infra annotations for OCP 4.14+

- pkg/openstackprovisionserver/deployment.go
Increase the PeriodSeconds to 10 and InitialDelaySeconds
to 30 for the openstakcprovisioningservers readinessProbe and
livenessProbe.
I am experiencing an issue where the pod never starts because
the probes are restarting the pod before the certificate generation
process has completed.
```
Normal  Killing  4m44s  kubelet  Container osp-httpd failed liveness probe, will be restarted
```
```
$ oc logs -n openstack pod/openstack-edpm-ipam-provisionserver-openstackprovisionserv6vcjp
Defaulted container "osp-httpd" out of: osp-httpd, osp-provision-ip-discovery-agent, init (init)
=> sourcing 10-set-mpm.sh ...
=> sourcing 20-copy-config.sh ...
=> sourcing 40-ssl-certs.sh ...
---> Generating SSL key pair for httpd...
```
> Provisioning server ready probe longe init delay

- pkg/openstackprovisionserver/deployment.go
A follow up to Pull #106, instead of bumping the readiness and liveness probe - add a startup probe instead. The startupProbe uses InitialDelaySeconds: 30.
> Use a startup probe for provisioning server

- api/v1beta1/openstackbaremetalset.go
- api/v1beta1/openstackbaremetalset_webhook.go
We can't use the whole of validation logic in dataplane webhook without reference to the baremetalset objects. Refactor part of it which vlidates the changes to bmhLabelSelector and hardwareReqs so that we can use it in dataplane webhook.
Also, changes some error strings to start with smallcase.
> Refactor validation logic to use in dataplane

- pkg/openstackprovisionserver/deployment.go
It seems that 30 seconds which were set before was not enough to generate SSL certificate and start osp-httpd container in the POD.
Problem was visible for example when this was deployed locally on dev machine.
To avoid that problem, and don't need to wait for livenessProbe to start for too long time, this patch removes initialDelay parameter of the startupProbe and instead sets:
failureThreshold: 30
periodSeconds: 10
That way startupProbe can fail 10 times before container will be restarted. But checks will be performed every 10 seconds and first successful check will stop startupProbe and start livenessProbe.
As livenessProbe will be always started after successful check of the startupProbe we don't need initialDelay there at all so it's removed also.
> Change initialDelay of startupProbe to the failureThreshold

- controllers/openstackprovisionserver_controller.go
This is required for CI where we install metal3 on CRC.
> Handle scenario where Provisioning resource does not exist

- .prow_ci.env
- Dockerfile
- Makefile
- Changed the build image to `ubi9/go-toolkit`
- Changed the base image to `ubi9/minimal`
- Added the default `GO_BUILD_EXTRA_ARGS="-tags strictfipsruntime"`
- Added the `GO_BUILD_EXTRA_ENV_ARGS` build argument to allow custom build arguments at build time. It defaults to `"CGO_ENABLED=1 GO111MODULE=on"`
- Those default parameters have been added to enable FIPS compliance
- Fixed indentation in Dockerfile
- Removed `TARGETOS` and `TARGETARCH` env vars.
- Added `DOCKER_BUILD_ARGS` variable in Makefile to pass custom parameters during podman build
- Added export `FAIL_FIPS_CHECK=true` in `.prow_ci.env` file to enable FIPS tests on prow
Closes: https://issues.redhat.com/browse/OSPRH-3375
> This change ensures the baremetal-operator is built with FIPS compliance

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- controllers/openstackbaremetalset_controller.go
This change is proposed so that a custom osContainerImageUrl can be provided in the dataplane spec. This makes it possible to deploy a modified image for purposes including hotfixes and custom hardware.
Other container images are also exposed for completeness.
> Expose provision server images in baremetal set

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- config/samples/baremetal_v1beta1_openstackbaremetalset.yaml
- pkg/openstackbaremetalset/baremetalhost.go
- templates/openstackbaremetalset/cloudinit/networkdata
Update the networkdata te
Change CtlPlaneIP to use a CIDR format (ip_addr/prefix).
Add a temporary compatibility layer utlizing a.b.c.d + CtlplaneNetmask to internally create the CIDR formated address.
In the future we can drop CtlplaneNetmask from OpenStackBaremetalSetSpec.
> Add IPv6 support for networkdata

- api/v1beta1/openstackbaremetalset_types.go
- api/v1beta1/openstackprovisionserver_types.go
- controllers/openstackbaremetalset_controller.go
- controllers/openstackprovisionserver_controller.go
Improves the deferred-status function to use the standardized pattern found in all (or at least most) other operators.  This also allows any error messages to appear in the CLI to help the user more easily discover problems.
> Align with standardized status pattern used across operators

- api/bases/baremetal.openstack.org_openstackprovisionservers.yaml
- api/v1beta1/openstackprovisionserver_types.go
- config/crd/bases/baremetal.openstack.org_openstackprovisionservers.yaml
We don't use the `ServiceAccount` field and it also seems to be absent from other operators
> Remove unused ServiceAccount field

- templates/openstackbaremetalset/cloudinit/networkdata
They fail when using ipv6 with unmarshalling error.
```
failed to provision: failed to unmarshal network_data.json from secret:
error converting YAML to JSON: yaml: line 10: mapping values are not
allowed in this context","errorVerbose":"error converting YAML to JSON:
```
Signed-off-by: rabi <ramishra@redhat.com>
> Quote certain fields in networkdata

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
This is the name of the Secret in the local namespace containing network configuration (e.g content of network_data.json) which is passed to the preprovisioning image. It is also passed to the Config Drive if not overridden by specifying NetworkData.
jira: https://issues.redhat.com/browse/OSPRH-5641
> Add PreprovisioningNetworkDataName to baremetalset spec

- pkg/openstackbaremetalset/baremetalhost.go
If already set in the BMH and not provided in baremetalSpec don't override preprovisioningNetworkDataName.
> Don't override preprovisioningNetworkDataName

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- controllers/openstackbaremetalset_controller.go
- controllers/openstackprovisionserver_controller.go
- go.mod
- go.sum
This patch follows the same pattern applied to the other operators, where we re-init the `conditions` at each reconcile loop. `Conditions` are re-evaluated and updated, keeping the `LastTransitionTime` for those that haven't changed (it avoids the transition from `True` to `Unknown` to `True` again).
In addition, the `observedGeneration` field is introduced, and it is used by the `openstack-operator` to check the `IsReady()` function for a particular `CR` in case a minor update is triggered. All the conditions are evaluated during the main `Reconcile` loop ( or the `reconcileNormal` function in some circumstances), hence the main `ReadyCondition` is updated within the same flow. The defer function still updates the `Resource` and `Mirror` the condition to the top-level `CR`.
Jira: …
> Re-init conditions each reconcile

- .github/workflows/build-openstack-baremetal-operator.yaml
Build the openstack-baremetal-operator-agent image using GitHub Action
workflow. This follows the same pattern as OSP director Operator.
Signed-off-by: Leif Madsen <lmadsen@redhat.com>
> Add agent builder to github workflows

- config/manifests/bases/openstack-baremetal-operator.clusterserviceversion.yaml
Also removes deprecated operators.openshift.io/infrastructure-features annotation.
https://issues.redhat.com/browse/OSPRH-7933
> Add required infrastructure annotations

- controllers/openstackbaremetalset_controller.go
- controllers/openstackprovisionserver_controller.go
Returning a non-`nil` `err` with a `RequeueAfter` result causes k8s to discard the explicit requeue and wait much longer than desired.
> Log "not found" error instead of returning it if using RequeueAfter

- controllers/openstackbaremetalset_controller.go
At present you can delete the OpenStackProvisionServer and it won't be re-created and manual changes to it won't be reset.
> Watch for owned OpenStackProvisionServer

- pkg/openstackbaremetalset/baremetalhost.go
Set bmhStatus.NetworkDataSecretName correctly when only PreprovisioningNetworkDataName is provided.
[OSPRH-10411](https://issues.redhat.com/browse/OSPRH-10411)
> Set status when only PreprovisioningNetworkDataName is used

- api/go.mod
- api/go.sum
- go.mod
- go.sum
As we bumped to go 1.21, we can now use a later version of BMO.
> Bump metal3-io/baremetal-operator

- Dockerfile.agent
This was missed when we bumped to 1.21.
Image build failed in https://github.com/openstack-k8s-operators/openstack-baremetal-operator/actions/runs/11123349986 and hence https://github.com/openstack-k8s-operators/openstack-operator/pull/1114 won't get the tag.
> Bump go-toolset for agent

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
- tests/functional/openstackbaremetalset_controller_test.go
We had initially introduced `preprovisioningNetworkDataName` field in `InstanceSpec` for users to have flexibility of setting it in `OpenStackDataPlaneNodeSet` CR for the individual nodes. We have had the implementation to fallback to using `preprovisioningNetworkDataName` for provisioning `networkData` if the later is not provided and the former is set.
However, we've noticed that this does not work when using coreos IPA ramdisk image as `ProvisioningImage` Builder expects the `preprovisioningNetworkDataName` to be in nmstate format, however for us during provisioning cloud-init expects it to be in openstack network_data.json format.
Therefore we would not replicate the metal3 behavior of falling back to `preprovisioningNetworkDataName` if `networkData` is not provided. We instead will …
> Remove PreprovisioningNetworkDataName

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
- tests/functional/openstackbaremetalset_controller_test.go
We had initially introduced preprovisioningNetworkDataName field in InstanceSpec for users to have flexibility of setting it in OpenStackDataPlaneNodeSet CR for the individual nodes. We have had the implementation to fallback to using preprovisioningNetworkDataName for networkData if the later is not provided and the former is set.
However, we've noticed that this does not work when using coreos IPA ramdisk image as ProvisioningImage Builder expects the preprovisioningNetworkDataName to be in nmstate format, however for us during provisioning cloud-init expects it to be in openstack network_data.json format.
Therefore we would not replicate the metal3 behavior of falling back to preprovisioningNetworkDataName if networkData is not provided. We instead will keep both network data for …
> Remove PreprovisioningNetworkData

- api/v1beta1/openstackprovisionserver.go
- api/v1beta1/openstackprovisionserver_types.go
- api/v1beta1/openstackprovisionserver_webhook.go
- controllers/openstackbaremetalset_controller.go
- pkg/openstackprovisionserver/const.go
Changes `OpenStackProvisionServer` auto-port-assignment to be cluster-scoped rather than namespaced.  This is necessary because provision server pods run with host networking.  Therefore, if two different provision server pods from two different namespaces are scheduled on the same node and use the same port, they will conflict and the second one will fail to run.  This resolves the problem by having the operator always consider the current port usage across all `OpenStackProvisionServer`s in the cluster when selecting a new port for a new `OpenStackProvisionServer`.  In this manner, we avoid duplicates in auto-generated port assignments.
Jira: [OSPRH-11494](https://issues.redhat.com//browse/OSPRH-11494)
> [OSPRH-11494] Make auto port assignment for OSProvServer cluster-scoped

- api/bases/baremetal.openstack.org_openstackprovisionservers.yaml
- api/v1beta1/openstackprovisionserver.go
- api/v1beta1/openstackprovisionserver_types.go
- api/v1beta1/openstackprovisionserver_webhook.go
- config/crd/bases/baremetal.openstack.org_openstackprovisionservers.yaml
- controllers/openstackbaremetalset_controller.go
This validates both user provided and auto assigned ports to be in the expected range.
Jira: https://issues.redhat.com/browse/OSPRH-11780
> Add validation for provisionserver port range

- Makefile
The new force-bump target bumps operator and lib-common dependencies of
this operator by tracking the same branch from these dependencies.
Related: [OSPRH-8355](https://issues.redhat.com//browse/OSPRH-8355)
> [make]Add force-bump target to bump operator deps

- Makefile
The new force-bump target bumps operator and lib-common dependencies of this operator by tracking the same branch from these dependencies.
18.0-fr1 only change:
* resolve the merge conflict in Makefile due to 80771af is not in 18.0-fr1
* switched the branch target of force-bump to 18.0-fr1
Related: [OSPRH-8355](https://issues.redhat.com//browse/OSPRH-8355)
(cherry picked from commit 38113a0073ee9372a53e464ce532fefa02351558)
> [18.0-fr1][make]Add force-bump target to bump operator deps

- templates/openstackbaremetalset/cloudinit/userdata
By default, root login is disabled.
> Enable root login when root password has been set

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- tests/functional/openstackbaremetalset_controller_test.go
Since this parameter is optional, we shouldn't set a default. This change removes the default for the param which will allow us to entirely remove the unused parameter once other projects have removed references to it.
Related: https://issues.redhat.com/browse/OSPRH-12304
> Remove default for optional CtlplaneNetmask

- api/v1beta1/openstackbaremetalset_types.go
- api/v1beta1/openstackbaremetalset_webhook.go
- tests/functional/openstackbaremetalset_controller_test.go
This was missed in the earlier PR. Also moves domain back to the OpenStackBaremetalSetTemplateSpec as there is no way to get it from nodeset spec.
> Refactor webhook method to use in openstack-operator

- api/v1beta1/openstackprovisionserver.go
- api/v1beta1/openstackprovisionserver_webhook.go
This mistakenly throws an error rather than using the next port in the port range.
Jira: https://issues.redhat.com/browse/OSPRH-12774
> Fix regression when assigning provision server port

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- tests/functional/openstackbaremetalset_controller_test.go
In the course of supporting the new OpenStack operator install paradigm, service operator webhooks will be removed.  This effects this operator.  As a result, `OpenStackBaremetalSet.spec.osImage` is no longer being defaulted.  It needs to be so for provisioning to work properly.  Therefore, since we are removing the webhooks in the new install paradigm, let's add a kubebuilder default for `osImage` to handle this case.  Note that the other previously-webhook-defaulted fields are defaulted by OpenStack operator (`OpenStackDataPlaneNodeSet` controller [1]) and thus do not need kubebuilder defaults.
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/f42bc846b6ef15db7c10ae8322e1d8916b569406/pkg/dataplane/baremetal.go#L62-L70
> Add kubebuilder default for OSBMS osImage

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
jira: https://issues.redhat.com/browse/OSPRH-12304
> Remove optional param CtlplaneNetmask

- config/default/manager_default_images.yaml
Accidental leftover from improvements to `OpenStackProvisionServer` agent from a few months ago
> Fix default image for provisioning agent

- .golangci.yaml
- containers/agent/checksum_discovery.go
- containers/agent/errors.go
- pkg/openstackbaremetalset/const.go
ref [OSPRH-9329](https://issues.redhat.com//browse/OSPRH-9329)
> Improve error handling

- api/bases/baremetal.openstack.org_openstackprovisionservers.yaml
- api/v1beta1/conditions.go
- api/v1beta1/openstackprovisionserver_types.go
- config/crd/bases/baremetal.openstack.org_openstackprovisionservers.yaml
- containers/agent/provision_ip_discovery.go
- controllers/openstackprovisionserver_controller.go
- pkg/openstackprovisionserver/errors.go
Let's improve the logic of the provisioning agent so that it reports problems with the provisioning interface back to the cluster and surfaces them in the `OpenStackProvisionServer` resource.
Jira: https://issues.redhat.com/browse/OSPRH-13507
> [OSPRH-13507] Surface prov interface errors reported by agent

- api/v1beta1/openstackbaremetalset.go
- api/v1beta1/openstackbaremetalset_webhook.go
- controllers/openstackbaremetalset_controller.go
As one can delete BMHs with consumerRef outside the general compute scale-down method, it's better to reconcile when for instance faulty BMHs are deleted and replace the computes with a new BMHs (if available).
Users just need to recreate a deployment to deploy on those newly created nodes.
jira: https://issues.redhat.com/browse/OSPRH-13948
> Reconcile for BMH delete events

- controllers/openstackbaremetalset_controller.go
Event will be triggerred when BMH status chnages, so we don't have to requeue explicitly.
> Don't requeue when checking for provisioning status

- templates/openstackprovisionserver/config/httpd.conf
Security improvement.  Tested in my environment via `curl -v -X TRACE http://192.168.111.10:6190/edpm-hardened-uefi.qcow2`.  Result looked good:
```
< HTTP/1.1 405 Method Not Allowed
< Date: Mon, 17 Mar 2025 09:26:36 GMT
< Server: Apache/2.4.62 (Red Hat Enterprise Linux) OpenSSL/3.2.2
< Allow: 
< Content-Length: 222
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method TRACE is not allowed for this URL.</p>
</body></html>
```
Jira: https://issues.redhat.com/browse/OSPRH-14672
> [OSPRH-14672] Disable HTTP TRACE in OpenStackProvisionServer

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
- tests/functional/openstackbaremetalset_controller_test.go
It could be different for different baremetal hosts based on the subnets they use.
jira: https://issues.redhat.com/browse/OSPRH-15221
> Move ctlplaneVlan and ctlplaneGateway to InstanceSpec

- api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- api/v1beta1/openstackbaremetalset_types.go
- config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
- pkg/openstackbaremetalset/baremetalhost.go
Allow overriding the `CtlplaneInterface` in the `InstanceSpec`, this will allow nodesets where one or more nodes use different interfaces for the ctlplane interface.
> Allow override CtlplaneInterface in InstanceSpec

- api/v1beta1/openstackbaremetalset.go
The Online flag indicatets wheater Metal3 should ensure the state of the host is powerd on when in a stable state.
With ironic fast-track if a host is created, and inspection is enabled the host will boot into ironic-python-agent - inspect ... then leave the node running with the agent ready for new commands - such as provision an image. When online is `false` the node will power-off after inspection, forcing another reboot to start the ironic-python-agent again.
Allowing `online: true` should result in faster deployment when inspection is enabled since it will use the fast-track mode.
I also think not allowing `online: true `this is counter intuitive, considering that Openshift examples in [docs]( https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/scalability_ …
> Allow using online: true in bmh spec
